package com;

public enum Union {
    SOUTH_EUROPE,
    NORTH_AMERICA,
    EAST_ASIA,
    SOUTH_AMERICA,
    MIDDLE_EUROPE,
    WEST_EUROPE,
    NORTH_EUROPE,
    WEST_ASIA,
    SMALL,
    THREE_NATIONS_CUP;
}